## Path to sample sheet
samplesheet: 'cqtl_atac_sample.txt'
bam_samplesheet: 'bam_atac_CQTL_all_samplesheet.txt'

## List columns to concatenate for file names 
fileNamesFrom: ['Project','Cell_Type','Condition']

sample_logic:
  Sample_handing: 'false'  # Set to 'false' to disable replicate/femur logic
  # Columns for building the main sample name
  base_name_columns: ['Project','Cell_Type','Condition']
  # Columns for grouping samples
  condition_column: 'Condition'
  control_group_value: 'normal' # Please change as needed for the name
  treatment_group_value: 'OA' # Please change as needed for the name
  # Columns for special cases (only used if Sample_handing is 'true')
  replicate_column: 'Bio_Rep'
  femur_column: 'Tissue'
  femur_donor_col: 'Donor'

#This section needs to be changed to current working directory
paths:
  outdir: atac_output
  base_dir: '/work/users/s/e/seyoun/atac_pipeline'

bwa_index: '/users/s/e/seyoun/Ref/genome/bwa_idx/hg38'
blacklist: '/work/users/s/e/seyoun/cQTL_caQTL/external/blacklist_region/ENCFF356LFX.bed.gz'
tss_annotation: '/users/s/e/seyoun/Ref/genome/gencode.v45.annotation.tss.bed.gz'
atac_qc_Rscript: './scripts/utils_workflow/atac_bamQC.R'

#atacqv
tssextension: '2000'

#verifybamid
verifybamid: '/users/s/e/seyoun/tools/verifyBamID_1.1.3/verifyBamID/bin/verifyBamID'

# Peak calling tools
peak_callers: ['macs2'] 


## WASP-specific 
wasp_options:
  wasp_dir: '/users/s/e/seyoun/tools/WASP'
  
# VCF paths
vcf_options:
  original_vcf: '/work/users/s/e/seyoun/cQTL_caQTL/geno_output/vcf/CQTL_COA9_10_ALL_qc.vcf.gz'

#deeptools
bin_size: '10'
effective_genome_size: '2747877702' # effective_genome_size for hg38 and 75bp read s 
normalize_option: 'RPGC'
chrsize: '/proj/phanstiel_lab/Reference/human/hg38/resources/hg38.chrom.filtered.sizes'

#bedops 
bedops_dir: "/users/s/e/seyoun/tools/bedops-2.4.41/bin"

#Rasqual
maf_threshold: 0.05
rasqual_dir: "/users/s/e/seyoun/tools/rasqual"
bam_dir: '/work/users/s/e/seyoun/cQTL_caQTL/atac_output/wasp/06_blk_filter'

## Software versions
fastqcVers: "0.12.1"
trim_galore: "0.6.7"
python: "3.12.4"
r: "4.5.0"
bwaVers: "0.7.17"
samtoolsVers: "1.22"
javaVers: "17.0.2"
waspVer: "2023-02"
picardVers: "3.4.0"
ataqvVers: "/work/users/s/e/seyoun/cQTL_caQTL/tools/ataqv-1.0.0/bin/ataqv"
deeptoolsVers: "3.5.4"
macs2: "2.2.9.1"
bedtools: "2.31.1"
subread: "2.1.1"
shapeit: "5.1.1"
bcftools: '1.22'
plink: "1.90b6.21"
plink2: "2.0.0-a.6.13"
