## Path to sample sheet
samplesheet: 'samplesheet.txt'

## List columns to concatenate for file names
mergeBy: ["Proj","Donor","Condition","Treatment"]
groupBy: ["Condition","Treatment"]
bamDir: "/work/users/s/e/seyoun/colabs/LCSP/seq_pipelines/rna_output/align"
bamSuffix: "_sorted.bam"
make_strand_bw: 'TRUE'

## References
gtf: '/proj/phanstiel_lab/Reference/human/hg38/annotations/gencode.v49.primary_assembly.annotation.gtf'
star: '/proj/phanstiel_lab/Reference/human/hg38/indices/star'
starsjdb: '/proj/phanstiel_lab/Reference/human/hg38/indices/star/sjdbList.fromGTF.out.tab'
fa: '/proj/phanstiel_lab/Reference/human/hg38/fasta/GRCh38.primary_assembly.genome.fa'

## verifyBamId version 2.0.1
verifybamid_bin: /users/s/e/seyoun/tools/VerifyBamID_2.0.1/bin/VerifyBamID
verifybamid_svdprefix: /users/s/e/seyoun/tools/VerifyBamID_2.0.1/resource/exome/1000g.phase3.10k.b38.exome.vcf.gz.dat
verifybamid_ref_fa: /proj/phanstiel_lab/Reference/human/hg38/fasta/GRCh38.primary_assembly.genome.fa

## rMATS options
t: 'paired'
readlength: 150
novelSS: 'FALSE'
comparison_group:
  - [norm_PBS, norm_DOXO]
  - [hypo_PBS, hypo_DOXO]

## salmon options
#gcBias: 'TRUE'
#seqBias: 'TRUE'
salmon: '/proj/phanstiel_lab/Reference/human/hg38/indices/salmon'
libtype: 'A'

## leafcutter
regtools: '/users/s/e/seyoun/tools/regtools_v1.0.0/build/regtools'
leafcutter2_env: 'leafcutter2'
leafcutter2_script: '/users/s/e/seyoun/tools/src/leafcutter2/scripts/leafcutter2.py'

## featureCounts
collapse_gtf: '/proj/phanstiel_lab/Reference/human/hg38/annotations/gencode.v49.primary_assembly.annotation.collapsed.gtf'
featureType: 'exon'
attrType: 'gene_id'

## Deeptools
normalize_option: 'CPM'
bin_size: '10'

## Software versions
fastqcVers: "0.12.1"
trim_galore: "0.6.7"
pythonVers: "3.12.4"
r: "4.5.0"
multiqcVers: "1.28"
samtoolsVers: "1.22"
starVers: '2.7.11b'
deeptoolsVers: "3.5.6"
rmats-turboVers: "4.3.0"
qualimapVers: '2.3'
pgizVers: '2.8'
salmonVers: "1.10.3"
picardVers: '3.4.0'
javaVers: '23.0.2'
subreadVers: '2.1.1'
rmats_turboVer: '4.3.0'
