## Path to sample sheet
samplesheet: 'samplesheet.txt'

## List columns to concatenate for file names
mergeBy: ['Proj','Condition','Bio_Rep','Tech_Rep']

## References
gtf: '/proj/phanstiel_lab/Reference/human/hg38/annotations/gencode.v49.primary_assembly.annotation.gtf'
star: '/proj/phanstiel_lab/Reference/human/hg38/indices/star'
starsjdb: '/proj/phanstiel_lab/Reference/human/hg38/indices/star/sjdbList.fromGTF.out.tab'
fa: '/proj/phanstiel_lab/Reference/human/hg38/fasta/GRCh38.primary_assembly.genome.fa'

## verifyBamId version 2.0.1
verifybamid: '/users/s/e/seyoun/tools/VerifyBamID_2.0.1/bin/VerifyBamID'

## rMATS options
t: 'paired'
readlength: 100
control: 'hESC'
case: 'NPC' # or the Neurons

## salmon options
salmon: '/proj/phanstiel_lab/Reference/human/hg38/indices/annotations/salmon_gentrome.fa.gz'
#gcBias: 'TRUE'
#seqBias: 'TRUE'
libtype: 'A'

## leafcutter
regtools: '/users/s/e/seyoun/tools/regtools_v1.0.0/build/regtools'
leafcutter2_env: 'leafcutter2'
leafcutter2_script: '/users/s/e/seyoun/tools/src/leafcutter2/scripts/leafcutter2.py'

## Software versions
fastqcVers: "0.12.1"
trim_galore: "0.6.7"
pythonVers: "3.12.4"
r: "4.5.0"
multiqcVers: "1.28"
samtoolsVers: "1.22"
starVers: '2.7.11b'
deeptoolsVers: "3.5.4"
rmats-turboVers: "4.3.0"
qualimapVers: '2.3'
pgizVers: '2.8'
salmonVers: "1.10.3"
picardVers: '3.4.0'
